# Generated by Django 5.1.2 on 2024-11-28 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(default='user', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.FileField(upload_to='pdf/')),
                ('id_compt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuit1.compt')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('les_question', models.TextField()),
                ('choix1', models.CharField(max_length=255)),
                ('choix2', models.CharField(max_length=255)),
                ('choix3', models.CharField(max_length=255)),
                ('reponce_user', models.CharField(max_length=255)),
                ('vrai_reponce', models.CharField(max_length=255)),
                ('id_compt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuit1.compt')),
            ],
        ),
    ]
